package com.zc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setPwd(java.lang.String pwd) {
		set("pwd", pwd);
	}
	
	public java.lang.String getPwd() {
		return getStr("pwd");
	}
	
	public void setUserStatus(java.lang.Integer userStatus) {
		set("userStatus", userStatus);
	}
	
	public java.lang.Integer getUserStatus() {
		return getInt("userStatus");
	}
	
	public void setCreateTime(java.lang.String createTime) {
		set("createTime", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("createTime");
	}
	
	public void setLoginTime(java.lang.String loginTime) {
		set("loginTime", loginTime);
	}
	
	public java.lang.String getLoginTime() {
		return getStr("loginTime");
	}
	
	public void setHeadImg(java.lang.String headImg) {
		set("headImg", headImg);
	}
	
	public java.lang.String getHeadImg() {
		return getStr("headImg");
	}
	
}

