package com.zc.model;

import com.zc.model.base.BaseData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Data extends BaseData<Data> {
    public static  Data dao=new Data().dao();
}

