package com.zc.model;

import com.zc.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static  User dao=new User().dao();


}

